/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as crons from "../crons.js";
import type * as custom_session from "../custom/session.js";
import type * as dao_casualPlayerDao from "../dao/casualPlayerDao.js";
import type * as dao_portalPlayerDao from "../dao/portalPlayerDao.js";
import type * as data_casualAsyncLeaderboardRowState from "../data/casualAsyncLeaderboardRowState.js";
import type * as data_casualMatchmakingConfig from "../data/casualMatchmakingConfig.js";
import type * as data_casualPayoutPolicy from "../data/casualPayoutPolicy.js";
import type * as data_casualPlayerStrategyTypes from "../data/casualPlayerStrategyTypes.js";
import type * as data_casualSeedTierPolicy from "../data/casualSeedTierPolicy.js";
import type * as data_casualTournamentRewardTypes from "../data/casualTournamentRewardTypes.js";
import type * as data_casualWeeklyLeagueConfig from "../data/casualWeeklyLeagueConfig.js";
import type * as data_partnerGameRegistry from "../data/partnerGameRegistry.js";
import type * as data_portalAdCoinConfig from "../data/portalAdCoinConfig.js";
import type * as data_portalAdEntryConfig from "../data/portalAdEntryConfig.js";
import type * as data_portalAdReplayConfig from "../data/portalAdReplayConfig.js";
import type * as data_portalAsyncLeaderboardRowState from "../data/portalAsyncLeaderboardRowState.js";
import type * as data_portalBadgeTemplates from "../data/portalBadgeTemplates.js";
import type * as data_portalDailyCheckinConfig from "../data/portalDailyCheckinConfig.js";
import type * as data_portalDailyPlayLimits from "../data/portalDailyPlayLimits.js";
import type * as data_portalEconomyGenerated from "../data/portalEconomyGenerated.js";
import type * as data_portalGiftCardEconomy from "../data/portalGiftCardEconomy.js";
import type * as data_portalInstanceWindow from "../data/portalInstanceWindow.js";
import type * as data_portalLobbyConfig from "../data/portalLobbyConfig.js";
import type * as data_portalLobbyOpsMode from "../data/portalLobbyOpsMode.js";
import type * as data_portalMatchmakingConfig from "../data/portalMatchmakingConfig.js";
import type * as data_portalPartnerReplaySettings from "../data/portalPartnerReplaySettings.js";
import type * as data_portalPartnerShopSettings from "../data/portalPartnerShopSettings.js";
import type * as data_portalPlayerStrategyTypes from "../data/portalPlayerStrategyTypes.js";
import type * as data_portalQuotaScope from "../data/portalQuotaScope.js";
import type * as data_portalSeasonHonorConfig from "../data/portalSeasonHonorConfig.js";
import type * as data_portalSeedTierPolicy from "../data/portalSeedTierPolicy.js";
import type * as data_portalShopCatalog from "../data/portalShopCatalog.js";
import type * as data_portalShopPartner from "../data/portalShopPartner.js";
import type * as data_portalTicketEntryConfig from "../data/portalTicketEntryConfig.js";
import type * as data_portalTournamentConfigs from "../data/portalTournamentConfigs.js";
import type * as data_portalTournamentRewardTypes from "../data/portalTournamentRewardTypes.js";
import type * as data_portalWeeklyLeagueConfig from "../data/portalWeeklyLeagueConfig.js";
import type * as http from "../http.js";
import type * as service_activity_casualActivityService from "../service/activity/casualActivityService.js";
import type * as service_ads_partnerAdReplayConfig from "../service/ads/partnerAdReplayConfig.js";
import type * as service_ads_portalAdCoinMutations from "../service/ads/portalAdCoinMutations.js";
import type * as service_ads_portalAdCoinQueries from "../service/ads/portalAdCoinQueries.js";
import type * as service_ads_portalAdCoinService from "../service/ads/portalAdCoinService.js";
import type * as service_ads_portalAdEntryMutations from "../service/ads/portalAdEntryMutations.js";
import type * as service_ads_portalAdEntryQueries from "../service/ads/portalAdEntryQueries.js";
import type * as service_ads_portalAdEntryService from "../service/ads/portalAdEntryService.js";
import type * as service_ads_portalAdReplayEligibility from "../service/ads/portalAdReplayEligibility.js";
import type * as service_ads_portalAdReplayMutations from "../service/ads/portalAdReplayMutations.js";
import type * as service_ads_portalAdReplayQueries from "../service/ads/portalAdReplayQueries.js";
import type * as service_ads_portalAdReplayService from "../service/ads/portalAdReplayService.js";
import type * as service_ads_portalEntryDailyUsage from "../service/ads/portalEntryDailyUsage.js";
import type * as service_ads_portalEntryUsageScope from "../service/ads/portalEntryUsageScope.js";
import type * as service_ads_portalPlayEntryOverlayMutations from "../service/ads/portalPlayEntryOverlayMutations.js";
import type * as service_ads_portalPlayEntryQueueRefund from "../service/ads/portalPlayEntryQueueRefund.js";
import type * as service_ads_portalRewardedAdModeQuery from "../service/ads/portalRewardedAdModeQuery.js";
import type * as service_ads_portalTicketEntryQueries from "../service/ads/portalTicketEntryQueries.js";
import type * as service_ads_portalTicketEntryService from "../service/ads/portalTicketEntryService.js";
import type * as service_ads_resolvePlayEntrySettings from "../service/ads/resolvePlayEntrySettings.js";
import type * as service_auth_jwtAccessSecret from "../service/auth/jwtAccessSecret.js";
import type * as service_auth_platformJwtVerify from "../service/auth/platformJwtVerify.js";
import type * as service_auth_portalAuth from "../service/auth/portalAuth.js";
import type * as service_backpack_grantCampaignVoucher from "../service/backpack/grantCampaignVoucher.js";
import type * as service_backpack_portalBackpackService from "../service/backpack/portalBackpackService.js";
import type * as service_badge_portalBadgeService from "../service/badge/portalBadgeService.js";
import type * as service_badge_portalBadgeUnlockLogic from "../service/badge/portalBadgeUnlockLogic.js";
import type * as service_botFill_botDifficultyConfig from "../service/botFill/botDifficultyConfig.js";
import type * as service_botFill_botRevealSchedule from "../service/botFill/botRevealSchedule.js";
import type * as service_botFill_botScoreSlots from "../service/botFill/botScoreSlots.js";
import type * as service_botFill_computeBotFillsCore from "../service/botFill/computeBotFillsCore.js";
import type * as service_botFill_durationFallback from "../service/botFill/durationFallback.js";
import type * as service_botFill_gameTypeConfig from "../service/botFill/gameTypeConfig.js";
import type * as service_botFill_rankSampling from "../service/botFill/rankSampling.js";
import type * as service_botFill_rolloutPick from "../service/botFill/rolloutPick.js";
import type * as service_botFill_seedRolloutBridge from "../service/botFill/seedRolloutBridge.js";
import type * as service_botFill_soloRankBand from "../service/botFill/soloRankBand.js";
import type * as service_botFill_soloRankEnforce from "../service/botFill/soloRankEnforce.js";
import type * as service_botFill_soloRankRecommend from "../service/botFill/soloRankRecommend.js";
import type * as service_botFill_triathlonBotFill from "../service/botFill/triathlonBotFill.js";
import type * as service_botPersona_portalBotPersonaDefaults from "../service/botPersona/portalBotPersonaDefaults.js";
import type * as service_botPersona_portalBotPersonaService from "../service/botPersona/portalBotPersonaService.js";
import type * as service_bridge_casualGameBridgeContract from "../service/bridge/casualGameBridgeContract.js";
import type * as service_bridge_casualGameBridgeSecret from "../service/bridge/casualGameBridgeSecret.js";
import type * as service_bridge_casualMatchSeedBridge from "../service/bridge/casualMatchSeedBridge.js";
import type * as service_bridge_casualSeedProvider from "../service/bridge/casualSeedProvider.js";
import type * as service_bridge_merchantCampaignBridge from "../service/bridge/merchantCampaignBridge.js";
import type * as service_bridge_merchantCampaignBridgeActions from "../service/bridge/merchantCampaignBridgeActions.js";
import type * as service_bridge_merchantCampaignBridgeEnv from "../service/bridge/merchantCampaignBridgeEnv.js";
import type * as service_campaignLeague_campaignLeagueBotFill from "../service/campaignLeague/campaignLeagueBotFill.js";
import type * as service_campaignLeague_campaignLeagueBotPersona from "../service/campaignLeague/campaignLeagueBotPersona.js";
import type * as service_campaignLeague_campaignLeagueBotPoints from "../service/campaignLeague/campaignLeagueBotPoints.js";
import type * as service_campaignLeague_campaignLeagueBotReveal from "../service/campaignLeague/campaignLeagueBotReveal.js";
import type * as service_campaignLeague_campaignLeagueConfig from "../service/campaignLeague/campaignLeagueConfig.js";
import type * as service_campaignLeague_campaignLeagueMerge from "../service/campaignLeague/campaignLeagueMerge.js";
import type * as service_campaignLeague_campaignLeagueQueries from "../service/campaignLeague/campaignLeagueQueries.js";
import type * as service_campaignLeague_campaignLeagueUpsert from "../service/campaignLeague/campaignLeagueUpsert.js";
import type * as service_campaignLeague_campaignMultiRankPoints from "../service/campaignLeague/campaignMultiRankPoints.js";
import type * as service_campaignLeague_campaignSoloPoints from "../service/campaignLeague/campaignSoloPoints.js";
import type * as service_economy_portalLobbyOpsMutations from "../service/economy/portalLobbyOpsMutations.js";
import type * as service_economy_portalWalletDao from "../service/economy/portalWalletDao.js";
import type * as service_economy_resolveEconomyScope from "../service/economy/resolveEconomyScope.js";
import type * as service_giftcard_giftCardActions from "../service/giftcard/giftCardActions.js";
import type * as service_giftcard_giftCardDevHarness from "../service/giftcard/giftCardDevHarness.js";
import type * as service_giftcard_giftCardEligibility from "../service/giftcard/giftCardEligibility.js";
import type * as service_giftcard_giftCardFulfillmentAction from "../service/giftcard/giftCardFulfillmentAction.js";
import type * as service_giftcard_giftCardOrderDao from "../service/giftcard/giftCardOrderDao.js";
import type * as service_giftcard_giftCardQueries from "../service/giftcard/giftCardQueries.js";
import type * as service_giftcard_tangoClient from "../service/giftcard/tangoClient.js";
import type * as service_giftcard_tangoTypes from "../service/giftcard/tangoTypes.js";
import type * as service_launch_portalLaunchActions from "../service/launch/portalLaunchActions.js";
import type * as service_launch_portalLaunchAuth from "../service/launch/portalLaunchAuth.js";
import type * as service_launch_portalLaunchMutations from "../service/launch/portalLaunchMutations.js";
import type * as service_launch_portalLaunchTypes from "../service/launch/portalLaunchTypes.js";
import type * as service_lobby_lobbyOfferingRewards from "../service/lobby/lobbyOfferingRewards.js";
import type * as service_lobby_portalLobbyMutations from "../service/lobby/portalLobbyMutations.js";
import type * as service_partner_portalPartnerGcOpsAdmin from "../service/partner/portalPartnerGcOpsAdmin.js";
import type * as service_partner_portalPartnerWipe from "../service/partner/portalPartnerWipe.js";
import type * as service_platformStatus from "../service/platformStatus.js";
import type * as service_player_playerManager from "../service/player/playerManager.js";
import type * as service_player_portalDisplayNameLookup from "../service/player/portalDisplayNameLookup.js";
import type * as service_player_portalPlayerProfile from "../service/player/portalPlayerProfile.js";
import type * as service_points_portalWeeklyPointsService from "../service/points/portalWeeklyPointsService.js";
import type * as service_reward_casualRewardRegistry from "../service/reward/casualRewardRegistry.js";
import type * as service_reward_portalDailyCheckinMutations from "../service/reward/portalDailyCheckinMutations.js";
import type * as service_reward_portalDailyCheckinQueries from "../service/reward/portalDailyCheckinQueries.js";
import type * as service_reward_portalDailyCheckinService from "../service/reward/portalDailyCheckinService.js";
import type * as service_season_casualSeasonService from "../service/season/casualSeasonService.js";
import type * as service_season_portalSeasonHonorService from "../service/season/portalSeasonHonorService.js";
import type * as service_season_resolvePortalSeasonHonor from "../service/season/resolvePortalSeasonHonor.js";
import type * as service_seedPool_catalogSeedHttp from "../service/seedPool/catalogSeedHttp.js";
import type * as service_seedPool_seedPoolAdmin from "../service/seedPool/seedPoolAdmin.js";
import type * as service_seedPool_seedPoolDevQueries from "../service/seedPool/seedPoolDevQueries.js";
import type * as service_seedPool_seedPoolQueries from "../service/seedPool/seedPoolQueries.js";
import type * as service_seedPool_seedPoolStore from "../service/seedPool/seedPoolStore.js";
import type * as service_seedPool_seedPoolValidators from "../service/seedPool/seedPoolValidators.js";
import type * as service_shop_partnerShopSettings from "../service/shop/partnerShopSettings.js";
import type * as service_shop_partnerShopSkuAdmin from "../service/shop/partnerShopSkuAdmin.js";
import type * as service_shop_portalShopService from "../service/shop/portalShopService.js";
import type * as service_shop_shopCatalogResolve from "../service/shop/shopCatalogResolve.js";
import type * as service_shop_shopOrdersQueries from "../service/shop/shopOrdersQueries.js";
import type * as service_shop_stripeCheckoutAction from "../service/shop/stripeCheckoutAction.js";
import type * as service_shop_stripeWebhookAction from "../service/shop/stripeWebhookAction.js";
import type * as service_task_casualTaskService from "../service/task/casualTaskService.js";
import type * as service_tournament_casualTournamentService from "../service/tournament/casualTournamentService.js";
import type * as service_tournament_join_campaignDailyPlayLimit from "../service/tournament/join/campaignDailyPlayLimit.js";
import type * as service_tournament_join_campaignPlayHistory from "../service/tournament/join/campaignPlayHistory.js";
import type * as service_tournament_join_campaignReplaySettingsValidator from "../service/tournament/join/campaignReplaySettingsValidator.js";
import type * as service_tournament_join_casualJoinMutations from "../service/tournament/join/casualJoinMutations.js";
import type * as service_tournament_join_casualMatchQueueSweep from "../service/tournament/join/casualMatchQueueSweep.js";
import type * as service_tournament_join_casualMatchSeedBinding from "../service/tournament/join/casualMatchSeedBinding.js";
import type * as service_tournament_join_casualMatchmaking from "../service/tournament/join/casualMatchmaking.js";
import type * as service_tournament_join_casualMatchmakingCore from "../service/tournament/join/casualMatchmakingCore.js";
import type * as service_tournament_join_casualMatchmakingProfile from "../service/tournament/join/casualMatchmakingProfile.js";
import type * as service_tournament_join_casualOpenTableActions from "../service/tournament/join/casualOpenTableActions.js";
import type * as service_tournament_join_casualOpenTableGuard from "../service/tournament/join/casualOpenTableGuard.js";
import type * as service_tournament_join_casualOpenTableMutations from "../service/tournament/join/casualOpenTableMutations.js";
import type * as service_tournament_join_casualTournamentActions from "../service/tournament/join/casualTournamentActions.js";
import type * as service_tournament_join_casualTournamentJoinCore from "../service/tournament/join/casualTournamentJoinCore.js";
import type * as service_tournament_join_portalDailyPlayLimit from "../service/tournament/join/portalDailyPlayLimit.js";
import type * as service_tournament_list_casualInstanceService from "../service/tournament/list/casualInstanceService.js";
import type * as service_tournament_list_casualTournamentQueries from "../service/tournament/list/casualTournamentQueries.js";
import type * as service_tournament_list_portalInstanceService from "../service/tournament/list/portalInstanceService.js";
import type * as service_tournament_replay_casualReplayKeepBestScore from "../service/tournament/replay/casualReplayKeepBestScore.js";
import type * as service_tournament_replay_casualReplayPassService from "../service/tournament/replay/casualReplayPassService.js";
import type * as service_tournament_replay_casualReplayTokens from "../service/tournament/replay/casualReplayTokens.js";
import type * as service_tournament_replay_casualRunReplay from "../service/tournament/replay/casualRunReplay.js";
import type * as service_tournament_settle_async_casualAsyncBotDueTime from "../service/tournament/settle/async/casualAsyncBotDueTime.js";
import type * as service_tournament_settle_async_casualAsyncBotPersist from "../service/tournament/settle/async/casualAsyncBotPersist.js";
import type * as service_tournament_settle_async_casualAsyncBotReveal from "../service/tournament/settle/async/casualAsyncBotReveal.js";
import type * as service_tournament_settle_async_casualAsyncTableSummary from "../service/tournament/settle/async/casualAsyncTableSummary.js";
import type * as service_tournament_settle_async_casualAsyncTypes from "../service/tournament/settle/async/casualAsyncTypes.js";
import type * as service_tournament_settle_campaignBridgeNotify from "../service/tournament/settle/campaignBridgeNotify.js";
import type * as service_tournament_settle_campaignPassRunRewardSnapshot from "../service/tournament/settle/campaignPassRunRewardSnapshot.js";
import type * as service_tournament_settle_casualArenaForceEnd from "../service/tournament/settle/casualArenaForceEnd.js";
import type * as service_tournament_settle_casualAsyncMatchFinalizeSchedule from "../service/tournament/settle/casualAsyncMatchFinalizeSchedule.js";
import type * as service_tournament_settle_casualHistorySettleReconcile from "../service/tournament/settle/casualHistorySettleReconcile.js";
import type * as service_tournament_settle_casualOpenRunReconcileAction from "../service/tournament/settle/casualOpenRunReconcileAction.js";
import type * as service_tournament_settle_casualOpenRunReconcileQueries from "../service/tournament/settle/casualOpenRunReconcileQueries.js";
import type * as service_tournament_settle_casualOpenRunSettleCheck from "../service/tournament/settle/casualOpenRunSettleCheck.js";
import type * as service_tournament_settle_casualOpenRunSettleCheckAction from "../service/tournament/settle/casualOpenRunSettleCheckAction.js";
import type * as service_tournament_settle_casualRunExpireCron from "../service/tournament/settle/casualRunExpireCron.js";
import type * as service_tournament_settle_casualRunMatchFinalize from "../service/tournament/settle/casualRunMatchFinalize.js";
import type * as service_tournament_settle_casualRunRewardsMutations from "../service/tournament/settle/casualRunRewardsMutations.js";
import type * as service_tournament_settle_casualRunScoreEffects from "../service/tournament/settle/casualRunScoreEffects.js";
import type * as service_tournament_settle_casualRunSettlementFill from "../service/tournament/settle/casualRunSettlementFill.js";
import type * as service_tournament_settle_playerMatchChallengeOutcome from "../service/tournament/settle/playerMatchChallengeOutcome.js";
import type * as service_tournament_settle_portalRunScoreEffects from "../service/tournament/settle/portalRunScoreEffects.js";
import type * as service_tournament_shared_casualPlayerGameTypes from "../service/tournament/shared/casualPlayerGameTypes.js";
import type * as service_tournament_shared_casualPlayerMatchStatus from "../service/tournament/shared/casualPlayerMatchStatus.js";
import type * as service_tournament_shared_casualPlayerTournamentRankStats from "../service/tournament/shared/casualPlayerTournamentRankStats.js";
import type * as service_tournament_shared_casualRankStatBuckets from "../service/tournament/shared/casualRankStatBuckets.js";
import type * as service_tournament_shared_casualRunSession from "../service/tournament/shared/casualRunSession.js";
import type * as service_tournament_shared_casualSessionOpenCore from "../service/tournament/shared/casualSessionOpenCore.js";
import type * as service_tournament_shared_casualTournamentTypes from "../service/tournament/shared/casualTournamentTypes.js";
import type * as service_tournament_shared_casualWatchReplaySnapshot from "../service/tournament/shared/casualWatchReplaySnapshot.js";
import type * as service_tournament_shared_portalRunMatchShell from "../service/tournament/shared/portalRunMatchShell.js";
import type * as service_tournament_shared_portalRunMatchShellAdmin from "../service/tournament/shared/portalRunMatchShellAdmin.js";
import type * as service_tournament_submit_casualIngestPlatformBotFill from "../service/tournament/submit/casualIngestPlatformBotFill.js";
import type * as service_tournament_submit_casualIngestTiming from "../service/tournament/submit/casualIngestTiming.js";
import type * as service_tournament_submit_casualMatchBotPlanningContext from "../service/tournament/submit/casualMatchBotPlanningContext.js";
import type * as service_tournament_submit_casualMatchSubmitContext from "../service/tournament/submit/casualMatchSubmitContext.js";
import type * as service_tournament_submit_casualPlayerGameIngest from "../service/tournament/submit/casualPlayerGameIngest.js";
import type * as service_tournament_submit_casualRunBridgeQueries from "../service/tournament/submit/casualRunBridgeQueries.js";
import type * as service_tournament_submit_casualRunIngestCore from "../service/tournament/submit/casualRunIngestCore.js";
import type * as service_tournament_submit_casualRunIngestHelpers from "../service/tournament/submit/casualRunIngestHelpers.js";
import type * as service_tournament_submit_casualRunIngestMutations from "../service/tournament/submit/casualRunIngestMutations.js";
import type * as service_weeklyLeague_casualWeeklyLeagueProfile from "../service/weeklyLeague/casualWeeklyLeagueProfile.js";
import type * as service_weeklyLeague_casualWeeklyLeagueService from "../service/weeklyLeague/casualWeeklyLeagueService.js";
import type * as service_weeklyLeague_casualWeeklyLeagueSettle from "../service/weeklyLeague/casualWeeklyLeagueSettle.js";
import type * as service_weeklyLeague_casualWeeklyLeagueXp from "../service/weeklyLeague/casualWeeklyLeagueXp.js";
import type * as service_weeklyLeague_portalWeeklyLeagueBotFill from "../service/weeklyLeague/portalWeeklyLeagueBotFill.js";
import type * as service_weeklyLeague_portalWeeklyLeagueBotPoints from "../service/weeklyLeague/portalWeeklyLeagueBotPoints.js";
import type * as service_weeklyLeague_portalWeeklyLeagueBotReveal from "../service/weeklyLeague/portalWeeklyLeagueBotReveal.js";
import type * as service_weeklyLeague_portalWeeklyLeagueClose from "../service/weeklyLeague/portalWeeklyLeagueClose.js";
import type * as service_weeklyLeague_portalWeeklyLeagueCohort from "../service/weeklyLeague/portalWeeklyLeagueCohort.js";
import type * as service_weeklyLeague_portalWeeklyLeagueDev from "../service/weeklyLeague/portalWeeklyLeagueDev.js";
import type * as service_weeklyLeague_portalWeeklyLeagueMatching from "../service/weeklyLeague/portalWeeklyLeagueMatching.js";
import type * as service_weeklyLeague_portalWeeklyLeagueQueries from "../service/weeklyLeague/portalWeeklyLeagueQueries.js";
import type * as service_weeklyLeague_portalWeeklyLeagueService from "../service/weeklyLeague/portalWeeklyLeagueService.js";
import type * as shared_constants from "../shared/constants.js";
import type * as shared_durationFallback from "../shared/durationFallback.js";
import type * as shared_pseudoUnit from "../shared/pseudoUnit.js";
import type * as shared_rankSampling from "../shared/rankSampling.js";
import type * as shared_rankStatBuckets from "../shared/rankStatBuckets.js";
import type * as shared_scoreQuantiles from "../shared/scoreQuantiles.js";
import type * as utils_casualTaskPeriod from "../utils/casualTaskPeriod.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  crons: typeof crons;
  "custom/session": typeof custom_session;
  "dao/casualPlayerDao": typeof dao_casualPlayerDao;
  "dao/portalPlayerDao": typeof dao_portalPlayerDao;
  "data/casualAsyncLeaderboardRowState": typeof data_casualAsyncLeaderboardRowState;
  "data/casualMatchmakingConfig": typeof data_casualMatchmakingConfig;
  "data/casualPayoutPolicy": typeof data_casualPayoutPolicy;
  "data/casualPlayerStrategyTypes": typeof data_casualPlayerStrategyTypes;
  "data/casualSeedTierPolicy": typeof data_casualSeedTierPolicy;
  "data/casualTournamentRewardTypes": typeof data_casualTournamentRewardTypes;
  "data/casualWeeklyLeagueConfig": typeof data_casualWeeklyLeagueConfig;
  "data/partnerGameRegistry": typeof data_partnerGameRegistry;
  "data/portalAdCoinConfig": typeof data_portalAdCoinConfig;
  "data/portalAdEntryConfig": typeof data_portalAdEntryConfig;
  "data/portalAdReplayConfig": typeof data_portalAdReplayConfig;
  "data/portalAsyncLeaderboardRowState": typeof data_portalAsyncLeaderboardRowState;
  "data/portalBadgeTemplates": typeof data_portalBadgeTemplates;
  "data/portalDailyCheckinConfig": typeof data_portalDailyCheckinConfig;
  "data/portalDailyPlayLimits": typeof data_portalDailyPlayLimits;
  "data/portalEconomyGenerated": typeof data_portalEconomyGenerated;
  "data/portalGiftCardEconomy": typeof data_portalGiftCardEconomy;
  "data/portalInstanceWindow": typeof data_portalInstanceWindow;
  "data/portalLobbyConfig": typeof data_portalLobbyConfig;
  "data/portalLobbyOpsMode": typeof data_portalLobbyOpsMode;
  "data/portalMatchmakingConfig": typeof data_portalMatchmakingConfig;
  "data/portalPartnerReplaySettings": typeof data_portalPartnerReplaySettings;
  "data/portalPartnerShopSettings": typeof data_portalPartnerShopSettings;
  "data/portalPlayerStrategyTypes": typeof data_portalPlayerStrategyTypes;
  "data/portalQuotaScope": typeof data_portalQuotaScope;
  "data/portalSeasonHonorConfig": typeof data_portalSeasonHonorConfig;
  "data/portalSeedTierPolicy": typeof data_portalSeedTierPolicy;
  "data/portalShopCatalog": typeof data_portalShopCatalog;
  "data/portalShopPartner": typeof data_portalShopPartner;
  "data/portalTicketEntryConfig": typeof data_portalTicketEntryConfig;
  "data/portalTournamentConfigs": typeof data_portalTournamentConfigs;
  "data/portalTournamentRewardTypes": typeof data_portalTournamentRewardTypes;
  "data/portalWeeklyLeagueConfig": typeof data_portalWeeklyLeagueConfig;
  http: typeof http;
  "service/activity/casualActivityService": typeof service_activity_casualActivityService;
  "service/ads/partnerAdReplayConfig": typeof service_ads_partnerAdReplayConfig;
  "service/ads/portalAdCoinMutations": typeof service_ads_portalAdCoinMutations;
  "service/ads/portalAdCoinQueries": typeof service_ads_portalAdCoinQueries;
  "service/ads/portalAdCoinService": typeof service_ads_portalAdCoinService;
  "service/ads/portalAdEntryMutations": typeof service_ads_portalAdEntryMutations;
  "service/ads/portalAdEntryQueries": typeof service_ads_portalAdEntryQueries;
  "service/ads/portalAdEntryService": typeof service_ads_portalAdEntryService;
  "service/ads/portalAdReplayEligibility": typeof service_ads_portalAdReplayEligibility;
  "service/ads/portalAdReplayMutations": typeof service_ads_portalAdReplayMutations;
  "service/ads/portalAdReplayQueries": typeof service_ads_portalAdReplayQueries;
  "service/ads/portalAdReplayService": typeof service_ads_portalAdReplayService;
  "service/ads/portalEntryDailyUsage": typeof service_ads_portalEntryDailyUsage;
  "service/ads/portalEntryUsageScope": typeof service_ads_portalEntryUsageScope;
  "service/ads/portalPlayEntryOverlayMutations": typeof service_ads_portalPlayEntryOverlayMutations;
  "service/ads/portalPlayEntryQueueRefund": typeof service_ads_portalPlayEntryQueueRefund;
  "service/ads/portalRewardedAdModeQuery": typeof service_ads_portalRewardedAdModeQuery;
  "service/ads/portalTicketEntryQueries": typeof service_ads_portalTicketEntryQueries;
  "service/ads/portalTicketEntryService": typeof service_ads_portalTicketEntryService;
  "service/ads/resolvePlayEntrySettings": typeof service_ads_resolvePlayEntrySettings;
  "service/auth/jwtAccessSecret": typeof service_auth_jwtAccessSecret;
  "service/auth/platformJwtVerify": typeof service_auth_platformJwtVerify;
  "service/auth/portalAuth": typeof service_auth_portalAuth;
  "service/backpack/grantCampaignVoucher": typeof service_backpack_grantCampaignVoucher;
  "service/backpack/portalBackpackService": typeof service_backpack_portalBackpackService;
  "service/badge/portalBadgeService": typeof service_badge_portalBadgeService;
  "service/badge/portalBadgeUnlockLogic": typeof service_badge_portalBadgeUnlockLogic;
  "service/botFill/botDifficultyConfig": typeof service_botFill_botDifficultyConfig;
  "service/botFill/botRevealSchedule": typeof service_botFill_botRevealSchedule;
  "service/botFill/botScoreSlots": typeof service_botFill_botScoreSlots;
  "service/botFill/computeBotFillsCore": typeof service_botFill_computeBotFillsCore;
  "service/botFill/durationFallback": typeof service_botFill_durationFallback;
  "service/botFill/gameTypeConfig": typeof service_botFill_gameTypeConfig;
  "service/botFill/rankSampling": typeof service_botFill_rankSampling;
  "service/botFill/rolloutPick": typeof service_botFill_rolloutPick;
  "service/botFill/seedRolloutBridge": typeof service_botFill_seedRolloutBridge;
  "service/botFill/soloRankBand": typeof service_botFill_soloRankBand;
  "service/botFill/soloRankEnforce": typeof service_botFill_soloRankEnforce;
  "service/botFill/soloRankRecommend": typeof service_botFill_soloRankRecommend;
  "service/botFill/triathlonBotFill": typeof service_botFill_triathlonBotFill;
  "service/botPersona/portalBotPersonaDefaults": typeof service_botPersona_portalBotPersonaDefaults;
  "service/botPersona/portalBotPersonaService": typeof service_botPersona_portalBotPersonaService;
  "service/bridge/casualGameBridgeContract": typeof service_bridge_casualGameBridgeContract;
  "service/bridge/casualGameBridgeSecret": typeof service_bridge_casualGameBridgeSecret;
  "service/bridge/casualMatchSeedBridge": typeof service_bridge_casualMatchSeedBridge;
  "service/bridge/casualSeedProvider": typeof service_bridge_casualSeedProvider;
  "service/bridge/merchantCampaignBridge": typeof service_bridge_merchantCampaignBridge;
  "service/bridge/merchantCampaignBridgeActions": typeof service_bridge_merchantCampaignBridgeActions;
  "service/bridge/merchantCampaignBridgeEnv": typeof service_bridge_merchantCampaignBridgeEnv;
  "service/campaignLeague/campaignLeagueBotFill": typeof service_campaignLeague_campaignLeagueBotFill;
  "service/campaignLeague/campaignLeagueBotPersona": typeof service_campaignLeague_campaignLeagueBotPersona;
  "service/campaignLeague/campaignLeagueBotPoints": typeof service_campaignLeague_campaignLeagueBotPoints;
  "service/campaignLeague/campaignLeagueBotReveal": typeof service_campaignLeague_campaignLeagueBotReveal;
  "service/campaignLeague/campaignLeagueConfig": typeof service_campaignLeague_campaignLeagueConfig;
  "service/campaignLeague/campaignLeagueMerge": typeof service_campaignLeague_campaignLeagueMerge;
  "service/campaignLeague/campaignLeagueQueries": typeof service_campaignLeague_campaignLeagueQueries;
  "service/campaignLeague/campaignLeagueUpsert": typeof service_campaignLeague_campaignLeagueUpsert;
  "service/campaignLeague/campaignMultiRankPoints": typeof service_campaignLeague_campaignMultiRankPoints;
  "service/campaignLeague/campaignSoloPoints": typeof service_campaignLeague_campaignSoloPoints;
  "service/economy/portalLobbyOpsMutations": typeof service_economy_portalLobbyOpsMutations;
  "service/economy/portalWalletDao": typeof service_economy_portalWalletDao;
  "service/economy/resolveEconomyScope": typeof service_economy_resolveEconomyScope;
  "service/giftcard/giftCardActions": typeof service_giftcard_giftCardActions;
  "service/giftcard/giftCardDevHarness": typeof service_giftcard_giftCardDevHarness;
  "service/giftcard/giftCardEligibility": typeof service_giftcard_giftCardEligibility;
  "service/giftcard/giftCardFulfillmentAction": typeof service_giftcard_giftCardFulfillmentAction;
  "service/giftcard/giftCardOrderDao": typeof service_giftcard_giftCardOrderDao;
  "service/giftcard/giftCardQueries": typeof service_giftcard_giftCardQueries;
  "service/giftcard/tangoClient": typeof service_giftcard_tangoClient;
  "service/giftcard/tangoTypes": typeof service_giftcard_tangoTypes;
  "service/launch/portalLaunchActions": typeof service_launch_portalLaunchActions;
  "service/launch/portalLaunchAuth": typeof service_launch_portalLaunchAuth;
  "service/launch/portalLaunchMutations": typeof service_launch_portalLaunchMutations;
  "service/launch/portalLaunchTypes": typeof service_launch_portalLaunchTypes;
  "service/lobby/lobbyOfferingRewards": typeof service_lobby_lobbyOfferingRewards;
  "service/lobby/portalLobbyMutations": typeof service_lobby_portalLobbyMutations;
  "service/partner/portalPartnerGcOpsAdmin": typeof service_partner_portalPartnerGcOpsAdmin;
  "service/partner/portalPartnerWipe": typeof service_partner_portalPartnerWipe;
  "service/platformStatus": typeof service_platformStatus;
  "service/player/playerManager": typeof service_player_playerManager;
  "service/player/portalDisplayNameLookup": typeof service_player_portalDisplayNameLookup;
  "service/player/portalPlayerProfile": typeof service_player_portalPlayerProfile;
  "service/points/portalWeeklyPointsService": typeof service_points_portalWeeklyPointsService;
  "service/reward/casualRewardRegistry": typeof service_reward_casualRewardRegistry;
  "service/reward/portalDailyCheckinMutations": typeof service_reward_portalDailyCheckinMutations;
  "service/reward/portalDailyCheckinQueries": typeof service_reward_portalDailyCheckinQueries;
  "service/reward/portalDailyCheckinService": typeof service_reward_portalDailyCheckinService;
  "service/season/casualSeasonService": typeof service_season_casualSeasonService;
  "service/season/portalSeasonHonorService": typeof service_season_portalSeasonHonorService;
  "service/season/resolvePortalSeasonHonor": typeof service_season_resolvePortalSeasonHonor;
  "service/seedPool/catalogSeedHttp": typeof service_seedPool_catalogSeedHttp;
  "service/seedPool/seedPoolAdmin": typeof service_seedPool_seedPoolAdmin;
  "service/seedPool/seedPoolDevQueries": typeof service_seedPool_seedPoolDevQueries;
  "service/seedPool/seedPoolQueries": typeof service_seedPool_seedPoolQueries;
  "service/seedPool/seedPoolStore": typeof service_seedPool_seedPoolStore;
  "service/seedPool/seedPoolValidators": typeof service_seedPool_seedPoolValidators;
  "service/shop/partnerShopSettings": typeof service_shop_partnerShopSettings;
  "service/shop/partnerShopSkuAdmin": typeof service_shop_partnerShopSkuAdmin;
  "service/shop/portalShopService": typeof service_shop_portalShopService;
  "service/shop/shopCatalogResolve": typeof service_shop_shopCatalogResolve;
  "service/shop/shopOrdersQueries": typeof service_shop_shopOrdersQueries;
  "service/shop/stripeCheckoutAction": typeof service_shop_stripeCheckoutAction;
  "service/shop/stripeWebhookAction": typeof service_shop_stripeWebhookAction;
  "service/task/casualTaskService": typeof service_task_casualTaskService;
  "service/tournament/casualTournamentService": typeof service_tournament_casualTournamentService;
  "service/tournament/join/campaignDailyPlayLimit": typeof service_tournament_join_campaignDailyPlayLimit;
  "service/tournament/join/campaignPlayHistory": typeof service_tournament_join_campaignPlayHistory;
  "service/tournament/join/campaignReplaySettingsValidator": typeof service_tournament_join_campaignReplaySettingsValidator;
  "service/tournament/join/casualJoinMutations": typeof service_tournament_join_casualJoinMutations;
  "service/tournament/join/casualMatchQueueSweep": typeof service_tournament_join_casualMatchQueueSweep;
  "service/tournament/join/casualMatchSeedBinding": typeof service_tournament_join_casualMatchSeedBinding;
  "service/tournament/join/casualMatchmaking": typeof service_tournament_join_casualMatchmaking;
  "service/tournament/join/casualMatchmakingCore": typeof service_tournament_join_casualMatchmakingCore;
  "service/tournament/join/casualMatchmakingProfile": typeof service_tournament_join_casualMatchmakingProfile;
  "service/tournament/join/casualOpenTableActions": typeof service_tournament_join_casualOpenTableActions;
  "service/tournament/join/casualOpenTableGuard": typeof service_tournament_join_casualOpenTableGuard;
  "service/tournament/join/casualOpenTableMutations": typeof service_tournament_join_casualOpenTableMutations;
  "service/tournament/join/casualTournamentActions": typeof service_tournament_join_casualTournamentActions;
  "service/tournament/join/casualTournamentJoinCore": typeof service_tournament_join_casualTournamentJoinCore;
  "service/tournament/join/portalDailyPlayLimit": typeof service_tournament_join_portalDailyPlayLimit;
  "service/tournament/list/casualInstanceService": typeof service_tournament_list_casualInstanceService;
  "service/tournament/list/casualTournamentQueries": typeof service_tournament_list_casualTournamentQueries;
  "service/tournament/list/portalInstanceService": typeof service_tournament_list_portalInstanceService;
  "service/tournament/replay/casualReplayKeepBestScore": typeof service_tournament_replay_casualReplayKeepBestScore;
  "service/tournament/replay/casualReplayPassService": typeof service_tournament_replay_casualReplayPassService;
  "service/tournament/replay/casualReplayTokens": typeof service_tournament_replay_casualReplayTokens;
  "service/tournament/replay/casualRunReplay": typeof service_tournament_replay_casualRunReplay;
  "service/tournament/settle/async/casualAsyncBotDueTime": typeof service_tournament_settle_async_casualAsyncBotDueTime;
  "service/tournament/settle/async/casualAsyncBotPersist": typeof service_tournament_settle_async_casualAsyncBotPersist;
  "service/tournament/settle/async/casualAsyncBotReveal": typeof service_tournament_settle_async_casualAsyncBotReveal;
  "service/tournament/settle/async/casualAsyncTableSummary": typeof service_tournament_settle_async_casualAsyncTableSummary;
  "service/tournament/settle/async/casualAsyncTypes": typeof service_tournament_settle_async_casualAsyncTypes;
  "service/tournament/settle/campaignBridgeNotify": typeof service_tournament_settle_campaignBridgeNotify;
  "service/tournament/settle/campaignPassRunRewardSnapshot": typeof service_tournament_settle_campaignPassRunRewardSnapshot;
  "service/tournament/settle/casualArenaForceEnd": typeof service_tournament_settle_casualArenaForceEnd;
  "service/tournament/settle/casualAsyncMatchFinalizeSchedule": typeof service_tournament_settle_casualAsyncMatchFinalizeSchedule;
  "service/tournament/settle/casualHistorySettleReconcile": typeof service_tournament_settle_casualHistorySettleReconcile;
  "service/tournament/settle/casualOpenRunReconcileAction": typeof service_tournament_settle_casualOpenRunReconcileAction;
  "service/tournament/settle/casualOpenRunReconcileQueries": typeof service_tournament_settle_casualOpenRunReconcileQueries;
  "service/tournament/settle/casualOpenRunSettleCheck": typeof service_tournament_settle_casualOpenRunSettleCheck;
  "service/tournament/settle/casualOpenRunSettleCheckAction": typeof service_tournament_settle_casualOpenRunSettleCheckAction;
  "service/tournament/settle/casualRunExpireCron": typeof service_tournament_settle_casualRunExpireCron;
  "service/tournament/settle/casualRunMatchFinalize": typeof service_tournament_settle_casualRunMatchFinalize;
  "service/tournament/settle/casualRunRewardsMutations": typeof service_tournament_settle_casualRunRewardsMutations;
  "service/tournament/settle/casualRunScoreEffects": typeof service_tournament_settle_casualRunScoreEffects;
  "service/tournament/settle/casualRunSettlementFill": typeof service_tournament_settle_casualRunSettlementFill;
  "service/tournament/settle/playerMatchChallengeOutcome": typeof service_tournament_settle_playerMatchChallengeOutcome;
  "service/tournament/settle/portalRunScoreEffects": typeof service_tournament_settle_portalRunScoreEffects;
  "service/tournament/shared/casualPlayerGameTypes": typeof service_tournament_shared_casualPlayerGameTypes;
  "service/tournament/shared/casualPlayerMatchStatus": typeof service_tournament_shared_casualPlayerMatchStatus;
  "service/tournament/shared/casualPlayerTournamentRankStats": typeof service_tournament_shared_casualPlayerTournamentRankStats;
  "service/tournament/shared/casualRankStatBuckets": typeof service_tournament_shared_casualRankStatBuckets;
  "service/tournament/shared/casualRunSession": typeof service_tournament_shared_casualRunSession;
  "service/tournament/shared/casualSessionOpenCore": typeof service_tournament_shared_casualSessionOpenCore;
  "service/tournament/shared/casualTournamentTypes": typeof service_tournament_shared_casualTournamentTypes;
  "service/tournament/shared/casualWatchReplaySnapshot": typeof service_tournament_shared_casualWatchReplaySnapshot;
  "service/tournament/shared/portalRunMatchShell": typeof service_tournament_shared_portalRunMatchShell;
  "service/tournament/shared/portalRunMatchShellAdmin": typeof service_tournament_shared_portalRunMatchShellAdmin;
  "service/tournament/submit/casualIngestPlatformBotFill": typeof service_tournament_submit_casualIngestPlatformBotFill;
  "service/tournament/submit/casualIngestTiming": typeof service_tournament_submit_casualIngestTiming;
  "service/tournament/submit/casualMatchBotPlanningContext": typeof service_tournament_submit_casualMatchBotPlanningContext;
  "service/tournament/submit/casualMatchSubmitContext": typeof service_tournament_submit_casualMatchSubmitContext;
  "service/tournament/submit/casualPlayerGameIngest": typeof service_tournament_submit_casualPlayerGameIngest;
  "service/tournament/submit/casualRunBridgeQueries": typeof service_tournament_submit_casualRunBridgeQueries;
  "service/tournament/submit/casualRunIngestCore": typeof service_tournament_submit_casualRunIngestCore;
  "service/tournament/submit/casualRunIngestHelpers": typeof service_tournament_submit_casualRunIngestHelpers;
  "service/tournament/submit/casualRunIngestMutations": typeof service_tournament_submit_casualRunIngestMutations;
  "service/weeklyLeague/casualWeeklyLeagueProfile": typeof service_weeklyLeague_casualWeeklyLeagueProfile;
  "service/weeklyLeague/casualWeeklyLeagueService": typeof service_weeklyLeague_casualWeeklyLeagueService;
  "service/weeklyLeague/casualWeeklyLeagueSettle": typeof service_weeklyLeague_casualWeeklyLeagueSettle;
  "service/weeklyLeague/casualWeeklyLeagueXp": typeof service_weeklyLeague_casualWeeklyLeagueXp;
  "service/weeklyLeague/portalWeeklyLeagueBotFill": typeof service_weeklyLeague_portalWeeklyLeagueBotFill;
  "service/weeklyLeague/portalWeeklyLeagueBotPoints": typeof service_weeklyLeague_portalWeeklyLeagueBotPoints;
  "service/weeklyLeague/portalWeeklyLeagueBotReveal": typeof service_weeklyLeague_portalWeeklyLeagueBotReveal;
  "service/weeklyLeague/portalWeeklyLeagueClose": typeof service_weeklyLeague_portalWeeklyLeagueClose;
  "service/weeklyLeague/portalWeeklyLeagueCohort": typeof service_weeklyLeague_portalWeeklyLeagueCohort;
  "service/weeklyLeague/portalWeeklyLeagueDev": typeof service_weeklyLeague_portalWeeklyLeagueDev;
  "service/weeklyLeague/portalWeeklyLeagueMatching": typeof service_weeklyLeague_portalWeeklyLeagueMatching;
  "service/weeklyLeague/portalWeeklyLeagueQueries": typeof service_weeklyLeague_portalWeeklyLeagueQueries;
  "service/weeklyLeague/portalWeeklyLeagueService": typeof service_weeklyLeague_portalWeeklyLeagueService;
  "shared/constants": typeof shared_constants;
  "shared/durationFallback": typeof shared_durationFallback;
  "shared/pseudoUnit": typeof shared_pseudoUnit;
  "shared/rankSampling": typeof shared_rankSampling;
  "shared/rankStatBuckets": typeof shared_rankStatBuckets;
  "shared/scoreQuantiles": typeof shared_scoreQuantiles;
  "utils/casualTaskPeriod": typeof utils_casualTaskPeriod;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
