/**
 * 角色模型列表：public/assets/3d/glb/characters 下的 GLB 模型
 * 路径格式：/assets/3d/glb/characters/{folder}/model/{folder}.glb
 */

const GLB_BASE = "/assets/3d/glb/characters";

export interface CharacterModel {
    name: string;
    /** 角色文件夹名，用于拼路径 */
    slug: string;
}

function pathFor(slug: string): string {
    return `${GLB_BASE}/${slug}/model/${slug}.glb`;
}

/**
 * 所有角色（名称 + 文件夹名），与 public/assets/3d/glb/characters 下目录对应
 */
export const CHARACTER_LIST: CharacterModel[] = [
    { name: "Akedia", slug: "akedia" },
    { name: "Alien", slug: "alien" },
    { name: "Apollo", slug: "apollo" },
    { name: "Arcanewitch Redhat", slug: "arcanewitch_redhat" },
    { name: "Archer", slug: "archer" },
    { name: "Arctic Shaman", slug: "arcticshaman" },
    { name: "Arctic Totem", slug: "arctictotem" },
    { name: "Ares", slug: "ares" },
    { name: "Ares Darkwarrior", slug: "ares_darkwarrior" },
    { name: "Assassin", slug: "assassin" },
    { name: "Athena", slug: "athena" },
    { name: "Azar", slug: "azar" },
    { name: "Bajie", slug: "bajie" },
    { name: "Batory", slug: "batory" },
    { name: "Bear Warrior", slug: "bearwarrior" },
    { name: "Bear Warrior Cook", slug: "bearwarrior_cook" },
    { name: "Boar", slug: "boar" },
    { name: "Boar Punk", slug: "boar_punk" },
    { name: "Bombcrag", slug: "bombcrag" },
    { name: "Bunny", slug: "bunny" },
    { name: "Bunny Hat", slug: "bunny_hat" },
    { name: "Bunnybig", slug: "bunnybig" },
    { name: "Bunnybig Hat", slug: "bunnybig_hat" },
    { name: "Centaur", slug: "centaur" },
    { name: "Cervitaur", slug: "cervitaur" },
    { name: "Change", slug: "change" },
    { name: "Change Icy", slug: "change_icy" },
    { name: "Chinese Lion", slug: "chineselion" },
    { name: "Chomper", slug: "chomper" },
    { name: "Christmas Tree", slug: "christmastree" },
    { name: "Clownbox", slug: "clownbox" },
    { name: "Crocodile", slug: "crocodile" },
    { name: "Cupid", slug: "cupid" },
    { name: "Death", slug: "death" },
    { name: "Death Pumpkin", slug: "death_pumpkin" },
    { name: "Earth Element", slug: "earthelement" },
    { name: "Egg", slug: "egg" },
    { name: "Elephant", slug: "elephant" },
    { name: "Ent", slug: "ent" },
    { name: "Faerie Dragon", slug: "faeriedragon" },
    { name: "Fairy", slug: "fairy" },
    { name: "Fairy Flower", slug: "fairy_flower" },
    { name: "Fiammetta", slug: "fiammetta" },
    { name: "Fire Dragon", slug: "firedragon" },
    { name: "Fire Dragon Bone", slug: "firedragon_bonedragon" },
    { name: "Forest Drummer", slug: "forestdrummer" },
    { name: "Frankenstein", slug: "frankenstein" },
    { name: "Ginger", slug: "ginger" },
    { name: "Goblin Gamer", slug: "goblingamer" },
    { name: "Griffin", slug: "griffin" },
    { name: "Griffin Machine", slug: "griffin_machine" },
    { name: "Harpy", slug: "harpy" },
    { name: "Heliantos", slug: "heliantos" },
    { name: "Heliantos Dandelion", slug: "heliantos_dandelion" },
    { name: "Hellboy", slug: "hellboy" },
    { name: "Hellboy General", slug: "hellboy_general" },
    { name: "Hitalot", slug: "hitalot" },
    { name: "Hopper", slug: "hopper" },
    { name: "Ice Cart", slug: "icecart" },
    { name: "Ice Commander", slug: "icecommonder" },
    { name: "Ice Commander Hammerfrost", slug: "icecommonder_hammerfrost" },
    { name: "Ice Sucker", slug: "icesucker" },
    { name: "Ice Sucker Hammerfrost", slug: "icesucker_hammerfrost" },
    { name: "Ice Sucker Plus", slug: "icesuckerplus" },
    { name: "Ice Sucker Plus Hammerfrost", slug: "icesuckerplus_hammerfrost" },
    { name: "Ice Sucker Special", slug: "icesuckerspecial" },
    { name: "Ice Sucker Special Hammerfrost", slug: "icesuckerspecial_hammerfrost" },
    { name: "Infantry", slug: "infantry" },
    { name: "Jackal", slug: "jackal" },
    { name: "Jackmouse", slug: "jackmouse" },
    { name: "Jungle Shaman", slug: "jungleshaman" },
    { name: "Kabuto", slug: "kabuto" },
    { name: "Karasu", slug: "karasu" },
    { name: "Knight", slug: "knight" },
    { name: "Knight Motor", slug: "knight_motor" },
    { name: "Lamp", slug: "lamp" },
    { name: "Lava Dolphin", slug: "lavadolphin" },
    { name: "Liberty", slug: "liberty" },
    { name: "Lion", slug: "lion" },
    { name: "Little Centaur", slug: "littlecentaur" },
    { name: "Longicorn", slug: "longicorn" },
    { name: "Mad Robot", slug: "madrobot" },
    { name: "Marmot Miner", slug: "marmotminer" },
    { name: "Marmot Miner Rich", slug: "marmotminer_rich" },
    { name: "Matryoshka", slug: "matryoshka" },
    { name: "Matryoshka 1", slug: "matryoshka1" },
    { name: "Mecha Doctor", slug: "mechadoctor" },
    { name: "Medusa", slug: "medusa" },
    { name: "Medusa Lava", slug: "medusa_lava" },
    { name: "Mulan", slug: "mulan" },
    { name: "Mummy Pharaoh", slug: "mummypharaoh" },
    { name: "Ninja", slug: "ninja" },
    { name: "Orc", slug: "orc" },
    { name: "Orc Warrior", slug: "orcwarrior" },
    { name: "Orc Warrior Blackarmor", slug: "orcwarrior_blackarmor" },
    { name: "Paladin", slug: "paladin" },
    { name: "Paladin Darkknight", slug: "paladin_darkknight" },
    { name: "Panda", slug: "panda" },
    { name: "Panda Mecha", slug: "panda_mecha" },
    { name: "Panda Monk", slug: "panda_monk" },
    { name: "Pastor", slug: "pastor" },
    { name: "Patrick", slug: "patrick" },
    { name: "Phantom", slug: "phantom" },
    { name: "Phobos", slug: "phobos" },
    { name: "Pukak", slug: "pukak" },
    { name: "Puppetboxer", slug: "puppetboxer" },
    { name: "Rednose", slug: "rednose" },
    { name: "Rockman", slug: "rockman" },
    { name: "Santa", slug: "santa" },
    { name: "Shadow Minion", slug: "shadowminion" },
    { name: "Shadow Minion Pumpkin", slug: "shadowminion_pumpkin" },
    { name: "Shaman", slug: "shaman" },
    { name: "Sharkman", slug: "sharkman" },
    { name: "Sharpshooter", slug: "sharpshooter" },
    { name: "Skin Cupid Nurse", slug: "skincupidnurse" },
    { name: "Snow Maiden", slug: "snowmaiden" },
    { name: "Spider", slug: "spider" },
    { name: "Sumo", slug: "sumo" },
    { name: "Surrender", slug: "surrender" },
    { name: "Talis", slug: "talis" },
    { name: "Talis Cat", slug: "talis_cat" },
    { name: "Tauren", slug: "tauren" },
    { name: "Thor", slug: "thor" },
    { name: "Tiger", slug: "tiger" },
    { name: "Time Master", slug: "timemaster" },
    { name: "Time Master Green", slug: "timemaster_green" },
    { name: "Trap Addap", slug: "trapaddap" },
    { name: "Trap Speedinc", slug: "trapspeedinc" },
    { name: "Turkey", slug: "turkey" },
    { name: "Turtle Captain", slug: "turtulecaptain" },
    { name: "Turtle Captain Diamond", slug: "turtulecaptain_diamond" },
    { name: "Turtle Captain Koopa", slug: "turtulecaptain_koopa" },
    { name: "Valkyrie", slug: "valkyrie" },
    { name: "Werewolf", slug: "werewolf" },
    { name: "Wild Referee", slug: "wildreferee" },
    { name: "Wujing", slug: "wujing" },
    { name: "Wukong", slug: "wukong" },
    { name: "Wukong White", slug: "wukong_white" },
    { name: "Yeti", slug: "yeti" },
];

/** 根据 slug 得到 GLB 路径 */
export function getGlbPath(slug: string): string {
    return pathFor(slug);
}
