/**
 * 关卡教学元数据（与 docs/pedagogy_stage_matrix.md 同步）
 * 通过 getStageRuleConfig(ruleId) 合并进 StageRuleConfig.pedagogy
 */
import type { StagePedagogy } from "../types/stageRuleTypes";

export const PEDAGOGY_BY_RULE_ID: Record<string, StagePedagogy> = {
    "monster_rumble_challenge_bronze_boss_1": {
        playerTierAssumed: 0,
        playerTierTaught: 0,
        bossMechanicTier: 0,
        bossMonsterId: "monster_001",
        counterFocus: "none",
        tutorialNotes: "熟悉移动、回合与普攻。",
        allowedSkillIds: ["basic_attack"],
        /** 文案由 `pedagogyDynamicGuide` 按战场状态切换，完成仍为首回合普攻 cast */
        dynamicGuide: true,
    },
    "monster_rumble_challenge_bronze_boss_2": {
        playerTierAssumed: 1,
        playerTierTaught: 1,
        bossMechanicTier: 0,
        bossMonsterId: "monster_002",
        counterFocus: "none",
        tutorialNotes: "使用单体技能与普攻完成输出循环。",
    },
    "monster_rumble_challenge_bronze_boss_3": {
        playerTierAssumed: 1,
        playerTierTaught: 2,
        bossMechanicTier: 1,
        bossMonsterId: "monster_001",
        counterFocus: "none",
    },
    "monster_rumble_challenge_bronze_boss_4": {
        playerTierAssumed: 2,
        playerTierTaught: 2,
        bossMechanicTier: 1,
        bossMonsterId: "monster_002",
        counterFocus: "range",
        tutorialNotes: "注意射程与站位，避免被贴脸。",
    },
    "monster_rumble_challenge_bronze_boss_5": {
        playerTierAssumed: 2,
        playerTierTaught: 3,
        bossMechanicTier: 2,
        bossMonsterId: "monster_002",
        counterFocus: "none",
        tutorialNotes: "Boss 可能随血量改变行为（见 boss 阶段配置）。",
    },
    "monster_rumble_challenge_silver_boss_1": {
        playerTierAssumed: 3,
        playerTierTaught: 3,
        bossMechanicTier: 3,
        bossMonsterId: "monster_003",
        counterFocus: "role_dps",
        tutorialNotes: "场上出现护卫目标，优先处理或集火 Boss。",
        loanMonsterIds: ["monster_039"],
    },
    "monster_rumble_challenge_silver_boss_2": {
        playerTierAssumed: 3,
        playerTierTaught: 3,
        bossMechanicTier: 3,
        bossMonsterId: "monster_003",
        counterFocus: "none",
    },
    "monster_rumble_challenge_silver_boss_3": {
        playerTierAssumed: 3,
        playerTierTaught: 4,
        bossMechanicTier: 3,
        bossMonsterId: "monster_004",
        counterFocus: "role_tank",
    },
    "monster_rumble_challenge_silver_boss_4": {
        playerTierAssumed: 4,
        playerTierTaught: 4,
        bossMechanicTier: 3,
        bossMonsterId: "monster_004",
        counterFocus: "none",
    },
    "monster_rumble_challenge_silver_boss_5": {
        playerTierAssumed: 4,
        playerTierTaught: 4,
        bossMechanicTier: 4,
        bossMonsterId: "monster_004",
        counterFocus: "none",
    },
    "monster_rumble_challenge_gold_boss_1": {
        playerTierAssumed: 4,
        playerTierTaught: 4,
        bossMechanicTier: 4,
        bossMonsterId: "monster_005",
        counterFocus: "none",
    },
    "monster_rumble_challenge_gold_boss_2": {
        playerTierAssumed: 4,
        playerTierTaught: 5,
        bossMechanicTier: 4,
        bossMonsterId: "monster_005",
        counterFocus: "none",
    },
    "monster_rumble_challenge_gold_boss_3": {
        playerTierAssumed: 5,
        playerTierTaught: 5,
        bossMechanicTier: 4,
        bossMonsterId: "monster_006",
        counterFocus: "none",
    },
    "monster_rumble_challenge_gold_boss_4": {
        playerTierAssumed: 5,
        playerTierTaught: 5,
        bossMechanicTier: 4,
        bossMonsterId: "monster_006",
        counterFocus: "none",
    },
    "monster_rumble_challenge_gold_boss_5": {
        playerTierAssumed: 5,
        playerTierTaught: 5,
        bossMechanicTier: 4,
        bossMonsterId: "monster_006",
        counterFocus: "none",
    },
    "monster_rumble_arena_bronze": {
        playerTierAssumed: 2,
        bossMechanicTier: 1,
        bossMonsterId: "monster_001",
        counterFocus: "none",
        tutorialNotes: "竞技场：不限制技能，检验综合操作。",
    },
    "monster_rumble_farm_bronze_boss_1": {
        playerTierAssumed: 2,
        bossMechanicTier: 0,
        bossMonsterId: "monster_001",
        counterFocus: "none",
        tutorialNotes: "材料本：重复刷取碎片。",
    },
    "monster_rumble_daily_boss": {
        playerTierAssumed: 3,
        bossMechanicTier: 2,
        bossMonsterId: "monster_001",
        counterFocus: "none",
        tutorialNotes: "每日高额奖励，机制难度略高于主线同级。",
    },
    "monster_rumble_weekly_boss": {
        playerTierAssumed: 4,
        bossMechanicTier: 3,
        bossMonsterId: "monster_003",
        counterFocus: "none",
        tutorialNotes: "周常挑战，建议提升战力后再尝试。",
    },
};
