/**
 * Display-name word lists v1 — freeze length for stable indices.
 * Only append new words in later versions; never reorder/remove.
 */

export const DISPLAY_NAME_WORDLIST_VERSION = 1 as const;

/** Frozen v1 adjective pool (48). Indices 0..47 must stay stable. */
export const DISPLAY_NAME_ADJECTIVES_V1 = [
  "Neon",
  "Quiet",
  "Swift",
  "Bold",
  "Lucky",
  "Calm",
  "Bright",
  "Silent",
  "Wild",
  "Clever",
  "Rapid",
  "Cosmic",
  "Golden",
  "Silver",
  "Crimson",
  "Azure",
  "Misty",
  "Frosty",
  "Sunny",
  "Stormy",
  "Noble",
  "Nimble",
  "Steady",
  "Fierce",
  "Gentle",
  "Mighty",
  "Hidden",
  "Radiant",
  "Velvet",
  "Iron",
  "Jade",
  "Amber",
  "Coral",
  "Ivory",
  "Obsidian",
  "Polar",
  "Solar",
  "Lunar",
  "Crystal",
  "Ember",
  "Pepper",
  "Maple",
  "Cedar",
  "Olive",
  "Pearl",
  "Ruby",
  "Sapphire",
  "Topaz",
] as const;

/** Frozen v1 noun pool (48). Indices 0..47 must stay stable. */
export const DISPLAY_NAME_NOUNS_V1 = [
  "Fox",
  "River",
  "Hawk",
  "Wolf",
  "Owl",
  "Bear",
  "Lynx",
  "Drake",
  "Falcon",
  "Puma",
  "Tiger",
  "Panda",
  "Otter",
  "Heron",
  "Raven",
  "Sparrow",
  "Comet",
  "Orbit",
  "Nova",
  "Pulse",
  "Spark",
  "Blaze",
  "Frost",
  "Echo",
  "Pixel",
  "Rune",
  "Quest",
  "Trail",
  "Peak",
  "Glen",
  "Cove",
  "Dune",
  "Meadow",
  "Grove",
  "Brook",
  "Delta",
  "Ridge",
  "Vale",
  "Crest",
  "Shore",
  "Storm",
  "Thunder",
  "Shadow",
  "Ember",
  "Flare",
  "Drift",
  "Cascade",
  "Horizon",
] as const;

export type DisplayNameAdjectiveV1 = (typeof DISPLAY_NAME_ADJECTIVES_V1)[number];
export type DisplayNameNounV1 = (typeof DISPLAY_NAME_NOUNS_V1)[number];
