export type CasualTownAssetType = "tiles" | "decor" | "icons";

export interface CasualTownAssetCatalogEntry {
  id: string;
  type: CasualTownAssetType;
  src: string;
  width: number;
  height: number;
  row: number;
  column: number;
  anchorX: number;
  anchorY: number;
}

export const casualTownAssetCatalog = [
  {
    id: "grass_placement_tile",
    type: "tiles",
    src: new URL("./generated/tiles/grass_placement_tile.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 0,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "stone_plaza_tile",
    type: "tiles",
    src: new URL("./generated/tiles/stone_plaza_tile.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 0,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "curved_path_tile",
    type: "tiles",
    src: new URL("./generated/tiles/curved_path_tile.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 0,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "straight_path_tile",
    type: "tiles",
    src: new URL("./generated/tiles/straight_path_tile.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 0,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "flower_pedestal_base",
    type: "tiles",
    src: new URL("./generated/tiles/flower_pedestal_base.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 1,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "trophy_pedestal_base",
    type: "tiles",
    src: new URL("./generated/tiles/trophy_pedestal_base.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 1,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "badge_display_base",
    type: "tiles",
    src: new URL("./generated/tiles/badge_display_base.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 1,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "fountain_base",
    type: "tiles",
    src: new URL("./generated/tiles/fountain_base.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 1,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "home_nameplate_base",
    type: "tiles",
    src: new URL("./generated/tiles/home_nameplate_base.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 2,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "garden_plot",
    type: "tiles",
    src: new URL("./generated/tiles/garden_plot.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 2,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "water_edge_platform",
    type: "tiles",
    src: new URL("./generated/tiles/water_edge_platform.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 2,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "season_banner_base",
    type: "tiles",
    src: new URL("./generated/tiles/season_banner_base.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 2,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "golden_trophy_statue",
    type: "decor",
    src: new URL("./generated/decor/golden_trophy_statue.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 0,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "fountain",
    type: "decor",
    src: new URL("./generated/decor/fountain.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 0,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "badge_crystal_pedestal",
    type: "decor",
    src: new URL("./generated/decor/badge_crystal_pedestal.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 0,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "wooden_challenge_board",
    type: "decor",
    src: new URL("./generated/decor/wooden_challenge_board.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 0,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "flower_bed_cluster",
    type: "decor",
    src: new URL("./generated/decor/flower_bed_cluster.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 1,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "park_bench",
    type: "decor",
    src: new URL("./generated/decor/park_bench.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 1,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "cat_statue",
    type: "decor",
    src: new URL("./generated/decor/cat_statue.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 1,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "dog_statue",
    type: "decor",
    src: new URL("./generated/decor/dog_statue.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 1,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "windmill_ornament",
    type: "decor",
    src: new URL("./generated/decor/windmill_ornament.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 2,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "purple_season_banner",
    type: "decor",
    src: new URL("./generated/decor/purple_season_banner.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 2,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "flower_arch",
    type: "decor",
    src: new URL("./generated/decor/flower_arch.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 2,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "street_lamp",
    type: "decor",
    src: new URL("./generated/decor/street_lamp.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 2,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "treasure_chest",
    type: "decor",
    src: new URL("./generated/decor/treasure_chest.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 3,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "shop_canopy_stand",
    type: "decor",
    src: new URL("./generated/decor/shop_canopy_stand.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 3,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "heart_social_ornament",
    type: "decor",
    src: new URL("./generated/decor/heart_social_ornament.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 3,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "white_picket_fence",
    type: "decor",
    src: new URL("./generated/decor/white_picket_fence.png", import.meta.url).href,
    width: 384,
    height: 256,
    row: 3,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.82,
  },
  {
    id: "visit",
    type: "icons",
    src: new URL("./generated/icons/visit.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 0,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "like",
    type: "icons",
    src: new URL("./generated/icons/like.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 0,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "challenge",
    type: "icons",
    src: new URL("./generated/icons/challenge.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 0,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "trophy",
    type: "icons",
    src: new URL("./generated/icons/trophy.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 0,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "badge_gem",
    type: "icons",
    src: new URL("./generated/icons/badge_gem.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 1,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "home",
    type: "icons",
    src: new URL("./generated/icons/home.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 1,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "edit_layout",
    type: "icons",
    src: new URL("./generated/icons/edit_layout.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 1,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "invite_friend",
    type: "icons",
    src: new URL("./generated/icons/invite_friend.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 1,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "history_scroll",
    type: "icons",
    src: new URL("./generated/icons/history_scroll.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 2,
    column: 0,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "locked_decor",
    type: "icons",
    src: new URL("./generated/icons/locked_decor.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 2,
    column: 1,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "season_banner",
    type: "icons",
    src: new URL("./generated/icons/season_banner.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 2,
    column: 2,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  {
    id: "share_link",
    type: "icons",
    src: new URL("./generated/icons/share_link.png", import.meta.url).href,
    width: 384,
    height: 341,
    row: 2,
    column: 3,
    anchorX: 0.5,
    anchorY: 0.5,
  },
] as const satisfies readonly CasualTownAssetCatalogEntry[];

export type CasualTownAssetId = (typeof casualTownAssetCatalog)[number]["id"];

export const casualTownAssetsById = Object.fromEntries(
  casualTownAssetCatalog.map((asset) => [asset.id, asset])
) as Record<CasualTownAssetId, CasualTownAssetCatalogEntry>;

